version: '2.1'

services:
  
  postgres:
    image: postgres:latest
    volumes:
      #- ./development/database/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    container_name: postshop
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shoppingdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  shop-api:
    build:
      context: .
      dockerfile: development/Dockerfile
    ports:
      - "8686:8181"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_started
    container_name: shop-api
    environment:
      #- DB_URL=postgresql://postgres:5432/weatherdb?sslmode=disable
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - DB_HOST=localhost
      - DB_NAME=shoppingdb
      - DB_SSL_MODE=disable

      #- DB_URL=postgres://root:postgres@postgres:5432/shoppingdb?sslmode=disable